spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/newsdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 8080

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG